_BASE_: "Base-bagtricks.yml"

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: '/home/liuxinchen3/zhengjinkai/fast-reid/fast-reid-strange/pretrain_model/resnet50_ibn_a.pth.tar'
  HEADS:
    NUM_CLASSES: 575
  LOSSES:
    CE:
      EPSILON: 0.0

DATASETS:
  NAMES: ("VeRi",)
  TESTS: ("VeRi",)

SOLVER:
  IMS_PER_BATCH: 64
  MAX_ITER: 70800
  STEPS: [23600, 53100]
  WARMUP_ITERS: 5900

  LOG_PERIOD: 590
  CHECKPOINT_PERIOD: 23600

TEST:
  EVAL_PERIOD: 5900
  IMS_PER_BATCH: 128

OUTPUT_DIR: "logs/veri/64_4gpu_bot_woLabelSmooth"
