_BASE_: "Base-bagtricks.yml"

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: '/home/liuxinchen3/zhengjinkai/fast-reid/fast-reid-strange/pretrain_model/resnet50_ibn_a.pth.tar'
  HEADS:
    NUM_CLASSES: 30671

DATASETS:
  NAMES: ("VeRiWild",)
  TESTS: ("SamllVeRiWild", "MediumVeRiWild", "LargeVeRiWild",)

SOLVER:
  IMS_PER_BATCH: 128
  MAX_ITER: 260400
  STEPS: [86800, 195300]
  WARMUP_ITERS: 21700

  LOG_PERIOD: 2170
  CHECKPOINT_PERIOD: 86800

TEST:
  EVAL_PERIOD: 21700
  IMS_PER_BATCH: 256

OUTPUT_DIR: "logs/veriwild/128_4gpu_bot"
