_BASE_: "Base-Strongerbaseline.yml"

INPUT:
  DO_AUTOAUG: False
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    WITH_IBN: True
    WITH_NL: False
    PRETRAIN_PATH: "/home/liuxinchen3/zhengjinkai/fast-reid/pretrain_model/resnet50_ibn_a.pth.tar"

  HEADS:
    MARGIN: 0.15
    SCALE: 128
    CLS_LAYER: linear
    NUM_CLASSES: 575
  LOSSES:
    TRI:
      HARD_MINING: False
  OPEN_LAYERS: ''

SOLVER:
  IMS_PER_BATCH: 64
  MAX_ITER: 9000
  DELAY_ITERS: 1000000000
  STEPS: [3000, 6750]
  WARMUP_ITERS: 750
  FREEZE_ITERS: 0

  WEIGHT_DECAY_BIAS: 0.0005

  LOG_PERIOD: 100
  CHECKPOINT_PERIOD: 3000

  ETA_MIN_LR: 0.0
  SCHED: WarmupMultiStepLR

DATASETS:
  NAMES: ("VeRi",)
  TESTS: ("VeRi",)

DATALOADER:
  NUM_INSTANCE: 4

TEST:
  EVAL_PERIOD: 750
  IMS_PER_BATCH: 1024

OUTPUT_DIR: "logs/veri/debug"
