_BASE_: "Base-Strongerbaseline.yml"

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    WITH_IBN: True
    WITH_NL: True
    PRETRAIN_PATH: "/home/liuxinchen3/zhengjinkai/fast-reid/pretrain_model/resnet50_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 13164

SOLVER:
  IMS_PER_BATCH: 64
  MAX_ITER: 212400
  DELAY_ITERS: 106200
  WARMUP_ITERS: 17700
  FREEZE_ITERS: 17700

  LOG_PERIOD: 1770
  CHECKPOINT_PERIOD: 17700

DATASETS:
  NAMES: ("VehicleID",)
  TESTS: ("SmallVehicleID", "MediumVehicleID", "LargeVehicleID",)

TEST:
  EVAL_PERIOD: 17700
  IMS_PER_BATCH: 512

OUTPUT_DIR: "logs/vehicleid/resnet_ibn-nl-gem-circle_s64m0.35_loss-cos_delay-autoaug"
