_BASE_: "Base-Strongerbaseline.yml"

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    WITH_IBN: True
    WITH_NL: True
    PRETRAIN_PATH: "/home/liuxinchen3/zhengjinkai/fast-reid/fast-reid-strange/pretrain_model/resnet50_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 575

SOLVER:
  IMS_PER_BATCH: 256
  MAX_ITER: 18000
  DELAY_ITERS: 9000
  WARMUP_ITERS: 1500
  FREEZE_ITERS: 1500

  LOG_PERIOD: 150
  CHECKPOINT_PERIOD: 6000

DATASETS:
  NAMES: ("VeRi",)
  TESTS: ("VeRi",)

TEST:
  EVAL_PERIOD: 1500
  IMS_PER_BATCH: 512

OUTPUT_DIR: "logs/veri/256_4gpu_sbs"
